"""Copy legacy lumbar training scripts into ``nas/training_bundle`` for cloud zips."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from rsna2024_lumbar.nas.paths import BUNDLE_DIR, CONFIGS_DIR, NAS_DIR, REPO_ROOT

LEGACY_PY_NAMES = (
    "vit_nas_lumbar.py",
    "train_vit.py",
    "train_vit_lumbar.py",
    "lumbar_constants.py",
    "lumbar_dataset.py",
    "lumbar_gpu_runner.py",
    "lumbar_model.py",
    "lumbar_model_avengers.py",
    "lumbar_model_clam.py",
    "lumbar_model_cnn2d.py",
    "lumbar_model_cnn3d.py",
    "lumbar_model_factory.py",
    "lumbar_model_maxvit.py",
    "lumbar_model_maxvit3d.py",
    "lumbar_model_medsam.py",
    "lumbar_model_mil.py",
    "lumbar_model_mil3d.py",
    "lumbar_model_vit3d.py",
    "lumbar_pipeline.py",
    "lumbar_shared_split.py",
)


def default_legacy_root() -> Path | None:
    env = os.environ.get("LUMBAR_LEGACY_ROOT")
    if env:
        path = Path(env).expanduser()
        if path.is_dir():
            return path.resolve()
    candidates = [
        REPO_ROOT / ".." / "datasets_lumbar" / "rsna-2024-lumbar-spine-degenerative-classification",
        REPO_ROOT.parent / "datasets_lumbar" / "rsna-2024-lumbar-spine-degenerative-classification",
        Path(r"F:\datasets_lumbar\rsna-2024-lumbar-spine-degenerative-classification"),
    ]
    for candidate in candidates:
        resolved = candidate.resolve()
        if (resolved / "vit_nas_lumbar.py").is_file():
            return resolved
    return None


def collect_legacy_sources(legacy_root: Path) -> list[Path]:
    legacy_root = legacy_root.resolve()
    if not legacy_root.is_dir():
        raise FileNotFoundError(f"Legacy training root not found: {legacy_root}")
    missing: list[str] = []
    files: list[Path] = []
    for name in LEGACY_PY_NAMES:
        path = legacy_root / name
        if path.is_file():
            files.append(path)
        else:
            missing.append(name)
    if missing:
        raise FileNotFoundError(
            f"Legacy root {legacy_root} is missing: {', '.join(missing)}"
        )
    return files


def stage_training_bundle(
    legacy_root: Path,
    *,
    dest: Path | None = None,
    overwrite: bool = True,
) -> list[Path]:
    """Copy legacy modules + NAS JSON configs into ``training_bundle/``."""
    dest = (dest or BUNDLE_DIR).resolve()
    bundle_configs = dest / "configs"
    if dest.exists() and overwrite:
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)
    bundle_configs.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for src in collect_legacy_sources(legacy_root):
        out = dest / src.name
        shutil.copy2(src, out)
        written.append(out)
    for config in CONFIGS_DIR.glob("*.json"):
        out = bundle_configs / config.name
        shutil.copy2(config, out)
        written.append(out)
    readme = dest / "README.txt"
    readme.write_text(
        "Auto-generated by rsna2024_lumbar.nas.pack. Do not edit on cloud.\n",
        encoding="utf-8",
    )
    written.append(readme)
    return written


def iter_bundle_files(bundle_dir: Path | None = None) -> list[Path]:
    root = (bundle_dir or BUNDLE_DIR).resolve()
    if not root.is_dir():
        return []
    files: list[Path] = []
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.name != ".gitkeep":
            files.append(path)
    return files
