name: test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e ".[dev]"
      - name: fixtures present
        run: test -f rsna2024_lumbar/tests/fixtures/train.csv && test -d rsna2024_lumbar/tests/fixtures/train_images
      - run: pytest --tb=short
